### ISSUE TITLE
"returning" method for update queries

### ISSUE THREAD

**Issue by fraserpal** [bluerelay/windyquery#2]
It would be great to use the "returning" method to get modified records by "update" queries.

**Comment by petli-full** [comment]
thanks for raising the issue. It's already there, but for some reason was not applied to update. This has been fixed. Here's an example: https://github.com/bluerelay/windyquery#update
I will be much appreciated if you could confirm it works as expect.

**Comment by fraserpal** [comment]
It works. Are you going to release the changes?
